version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  pixmark:
    image: nickyops/pixmark:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

volumes:
  redis_data:
