version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  pixmark:
    build: .
    container_name: pixmark
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./app:/app

volumes:
  redis_data: