# Generated by Django 4.1.13 on 2024-05-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
